# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Temperatura', models.IntegerField()),
                ('Humedad', models.IntegerField()),
            ],
        ),
    ]
