# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 12:39
from __future__ import unicode_literals

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFICApp', '0002_auto_20161013_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='Timestamp',
            field=django_unixdatetimefield.fields.UnixDateTimeField(),
        ),
    ]
