# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-16 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFICApp', '0003_auto_20161013_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiente',
            name='Timestamp',
        ),
    ]
