# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 16:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFICApp', '0005_ambiente_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente10s',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('Temperatura', models.IntegerField()),
                ('Humedad', models.IntegerField()),
            ],
        ),
    ]
