# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFICApp', '0006_ambiente10s'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ambiente10s',
            new_name='Ambiente1m',
        ),
    ]
