# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-24 19:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFICApp', '0009_auto_20161119_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbienteMaxMin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('TemperaturaMax', models.IntegerField()),
                ('TemperaturaMin', models.IntegerField()),
            ],
        ),
    ]
