# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-24 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFICApp', '0011_auto_20161124_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambientestats',
            name='Fecha',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
