# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-12 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFICApp', '0012_auto_20161124_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='Zona',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='ambiente1m',
            name='Zona',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='ambientestats',
            name='Zona',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
