# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-16 17:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFICApp', '0013_auto_20170212_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zona', models.CharField(default=0, max_length=20)),
                ('Timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('Temperatura', models.IntegerField()),
                ('Humedad', models.IntegerField()),
            ],
        ),
    ]
