# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFICApp', '0017_auto_20170220_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente1m',
            name='Humedad1',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='ambiente1m',
            name='Humedad2',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='ambiente1m',
            name='Temperatura1',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='ambiente1m',
            name='Temperatura2',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='ambiente1m',
            name='Zona',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
