# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFICApp', '0019_auto_20170220_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiente1m',
            name='Humedad1',
        ),
        migrations.RemoveField(
            model_name='ambiente1m',
            name='Humedad2',
        ),
        migrations.RemoveField(
            model_name='ambiente1m',
            name='Temperatura1',
        ),
        migrations.RemoveField(
            model_name='ambiente1m',
            name='Temperatura2',
        ),
    ]
