# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFICApp', '0020_auto_20170220_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente1m',
            name='Zona',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
