# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFICApp', '0022_auto_20170220_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente1m',
            name='Humedad1',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ambiente1m',
            name='Humedad2',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ambiente1m',
            name='Temperatura1',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ambiente1m',
            name='Temperatura2',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
