# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFICApp', '0024_auto_20170220_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente1m',
            name='Humedad1',
            field=models.DecimalField(decimal_places=10, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='ambiente1m',
            name='Humedad2',
            field=models.DecimalField(decimal_places=10, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='ambiente1m',
            name='Temperatura1',
            field=models.DecimalField(decimal_places=10, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='ambiente1m',
            name='Temperatura2',
            field=models.DecimalField(decimal_places=10, max_digits=50, null=True),
        ),
    ]
