# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 18:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFICApp', '0028_delete_ambiente1m'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente1m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zona', models.CharField(default=0, max_length=20)),
                ('Timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('Temperatura1', models.IntegerField(null=True)),
                ('Humedad1', models.IntegerField(null=True)),
                ('Temperatura2', models.IntegerField(null=True)),
                ('Humedad2', models.IntegerField(null=True)),
            ],
        ),
    ]
