# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFICApp', '0029_ambiente1m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente1m',
            name='Zona',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='ambientestats',
            name='Zona',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
