# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFICApp', '0031_auto_20170220_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente1m',
            name='Test',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
