# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFICApp', '0034_remove_ambiente1m_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiente1m',
            name='Zona',
        ),
    ]
