# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-21 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFICApp', '0035_remove_ambiente1m_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='Humedad',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='Temperatura',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ambiente2',
            name='Humedad',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ambiente2',
            name='Temperatura',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ambientestats',
            name='TemperaturaMax',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ambientestats',
            name='TemperaturaMed',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ambientestats',
            name='TemperaturaMin',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
