# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-07 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFICApp', '0036_auto_20170221_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente1m',
            name='Led1State',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambiente1m',
            name='Led2State',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
    ]
