# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-08 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFICApp', '0037_auto_20170307_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente1m',
            name='Led1State',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ambiente1m',
            name='Led2State',
            field=models.IntegerField(null=True),
        ),
    ]
