# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-22 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFICApp', '0038_auto_20170308_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente1m',
            name='Activado',
            field=models.IntegerField(default=0),
        ),
    ]
