# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-22 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFICApp', '0039_ambiente1m_activado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente1m',
            name='Led1State',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ambiente1m',
            name='Led2State',
            field=models.IntegerField(default=0),
        ),
    ]
