# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-27 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFICApp', '0041_ajustes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajustes',
            name='Dias',
            field=models.IntegerField(default=0),
        ),
    ]
